"""
Meeting schemas.
"""
from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel
from uuid import UUID


class ActionItemResponse(BaseModel):
    id: UUID
    description: str
    owner: Optional[str] = None
    due_date: Optional[datetime] = None
    priority: str = "medium"
    status: str = "pending"
    reminder_id: Optional[str] = None
    created_at: datetime

    class Config:
        from_attributes = True


class MeetingSummary(BaseModel):
    """Meeting summary generated by AI."""
    discussion: Optional[str] = None
    key_points: Optional[List[str]] = None
    action_items: Optional[List[str]] = None
    attendees: Optional[List[str]] = None

    class Config:
        extra = "ignore"  # Ignore any extra fields


class MeetingResponse(BaseModel):
    id: UUID
    calendar_event_id: Optional[str] = None
    event_title: Optional[str] = None
    event_start: Optional[datetime] = None
    event_end: Optional[datetime] = None
    transcript: Optional[str] = None
    summary: Optional[MeetingSummary] = None
    project_id: Optional[UUID] = None
    action_items: List[ActionItemResponse] = []
    created_at: datetime

    class Config:
        from_attributes = True


class MeetingUploadResponse(BaseModel):
    id: UUID
    message: str
    transcript: Optional[str] = None
    summary: Optional[MeetingSummary] = None
